### ISSUE TITLE
memedit00 报错 Aborted

### ISSUE THREAD

**Issue by reunravel** [qaiu/c4droid-code#2]
游戏是64位的，启用了debug，搜索内存时报错，关闭debug可以正常使用，速度倒是真的快，甚至感觉比GG还快

**Comment by qaiu** [comment]
C4droid开断点报中断异常吗，是否开启悬浮窗权限，以及具体断点的位置提供下

**Comment by reunravel** [comment]
不是断点的时候报中断异常，是在搜索游戏数据的时候报错的，游戏的AndroidManifest.xml文件里设置了android:debuggable="true"

**Comment by qaiu** [comment]
> 不是断点的时候报中断异常，是在搜索游戏数据的时候报错的，游戏的AndroidManifest.xml文件里设置了android:debuggable="true"

导致Aborted的错误原因很多, 常见的是内存越界, 至于为什么安卓app开启调试后 内存搜索工具 会报异常 这个还不是很清楚, 目前该内存插件早停止维护, 有兴趣的话可以自己研究研究, 我觉得大概因为AndroidManifest.xml开启调试后可以通过外部方式进行动态调试, 内存Dump等 然后底层linux基址映射发生了变化, 导致搜索发生错误...
总之 以目前情况 可以给出结论 Memedit暂不支持apk的debug模式
MemoryTools在github也能找到源码 或许你可以试试那个

**Comment by qaiu** [comment]
> 不是断点的时候报中断异常，是在搜索游戏数据的时候报错的，游戏的AndroidManifest.xml文件里设置了android:debuggable="true"

导致Aborted的错误原因很多, 常见的是内存越界, 至于为什么安卓app开启调试后 内存搜索工具 会报异常 这个还不是很清楚, 目前该内存插件早停止维护, 有兴趣的话可以自己研究研究, 我觉得大概因为AndroidManifest.xml开启调试后可以通过外部方式进行动态调试, 内存Dump等 然后底层linux基址映射发生了变化, 导致搜索发生错误...
总之 以目前情况 可以给出结论 Memedit暂不支持apk的debug模式
MemoryTools在github也能找到源码 或许你可以试试那个
